version = 1

[merge]
automerge_label = "lgtm"
require_automerge_label = true
blacklist_title_regex = "^WIP.*"
blacklist_labels = ["hold", "work in progress"]
method = "squash"
delete_branch_on_merge = true
block_on_reviews_requested = false
notify_on_conflict = false
optimistic_updates = true

[merge.message]
title = "pull_request_title"
body = "pull_request_body"
include_pr_number = true
body_type = "markdown"
