{
  sudo: "required",
  dist: "trusty",
  addons: {
    apt: {
      sources: ["google-chrome"],
      packages: ["google-chrome-stable"]
    }
  },
  language: "node_js",
  node_js: ["8"],
  cache: {
    directories: ["node_modules"]
  },
  before_install: [
    "export DISPLAY=:99.0",
    "sh -e /etc/init.d/xvfb start",
    "sleep 3"
  ],
  before_cache: [
    "rm -rf node_modules/.cache"
  ],
  before_script: ["npm run bootstrap"],
  after_script: ["npm run coveralls"]
}
