language: node_js
node_js:
  - "node"
  - "6"
  - "4"
cache:
  yarn: true
  directories:
    - node_modules
install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash
  - export PATH=$HOME/.yarn/bin:$PATH
  - yarn --ignore-engines
after_script: npm run coveralls
