sudo: required
dist: trusty
addons:
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable
language: node_js
node_js:
  - "4"
  - "6"
cache:
  directories:
    - node_modules
before_install:
  - rm yarn.lock
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - sleep 3
script:
  - echo "No need to use npm test since it's done in the install section via 'npm prepublish'"
after_script: npm run coveralls
