environment:
  matrix:
    - nodejs_version: "8"

# Install scripts. (runs after repo cloning)
install:
  # Install Google Chrome for e2e testing
  - choco install --ignore-checksums googlechrome
  # Get the latest stable version of Node.js or io.js
  - ps: Install-Product node $env:nodejs_version x64
  # install modules
  - npm install
  - npm run bootstrap

# Post-install test scripts.
test_script:
  # Output useful info for debugging.
  - node --version
  - npm --version
  # run tests
  - npm test

# Don't actually build.
build: off