pool:
  vmImage: 'vs2017-win2016'

variables:
  NEXT_TELEMETRY_DISABLED: '1'

strategy:
  maxParallel: 10
  matrix:
    node-10-1:
      group: 1/2
      node_version: ^10.10.0
    node-10-2:
      group: 2/2
      node_version: ^10.10.0
    node-8-1:
      group: 1/2
      node_version: ^8.12.0
    node-8-2:
      group: 2/2
      node_version: ^8.12.0

steps:
  - task: NodeTool@0
    inputs:
      versionSpec: $(node_version)
    displayName: 'Install Node.js'

  - script: |
      yarn install
    displayName: 'Install dependencies'

  - script: |
      yarn check
    displayName: 'Yarn check'

  - script: |
      node run-tests.js -c 2 -g $(group) --hard-retry
    displayName: 'Run tests'
