on: release
name: Generate release stats
jobs:
  prStats:
    name: PR Stats
    runs-on: ubuntu-latest
    steps:
    - name: PR Stats
      uses: zeit/next-stats-action@master
      env:
        PR_STATS_COMMENT_TOKEN: ${{ secrets.PR_STATS_COMMENT_TOKEN }}
